
AllCops:
  NewCops: enable

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc']
  IgnoredMethods: ['describe', 'context']
  Max: 20

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
  Exclude: ['**/*.rake']

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

