name: Check Outdated

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1' 
      
jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up ruby  
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true 
      - name: Check Outdated
        run: bundle outdated rails
